categories:
- Data Managers
description: Run Enzbert model 
long_description: |
  This tool runs Enzbert model.
name: enzbert
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/enzbert
type: unrestricted
homepage_url: https://gitlab.inria.fr/nbuton/tfpc/-/tree/EnzBert_conda