categories:
- Data Managers
description: Install Enzbert model 
long_description: |
  This data manager retrieves Enzbert model data.
name: data_manager_enzbert
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_enzbert
type: unrestricted
homepage_url: https://gitlab.inria.fr/nbuton/tfpc/-/tree/EnzBert_conda